version: '3.1'

networks:
  metrics:
    driver: bridge
  database:
    driver: bridge

services:
  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: hotpdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - database

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    restart: always
    volumes:
      - "./prometheus/prometheus.yml://etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "8903:3000"
    networks:
      - metrics
      - database

  hazelcast:
    image: hazelcast/hazelcast
    restart: always
    environment:
      HZ_NETWORK_PUBLICADDRESS: "localhost:5701"
    ports:
      - "5701:5701"