version: '3.1'

networks:
  metrics:
    driver: bridge
  database:
    driver: bridge

services:
  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: hotpdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - database

  #  dbeaver:
  #    image: dbeaver/cloudbeaver:latest
  #    depends_on:
  #      - postgres
  #    ports:
  #      - "8901:8978"

  graphite:
    image: graphiteapp/graphite-statsd
    hostname: graphite
    restart: always
    ports:
      - "8902:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125"
      - "8126:8126"
    networks:
      - metrics

  pushgateway:
    image: prom/pushgateway
    hostname: pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    depends_on:
      - pushgateway
    restart: always
    volumes:
      - "./prometheus/prometheus.yml://etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "8903:3000"
    networks:
      - metrics
      - database